name: Tests
on:
  push:
    branches:
      - main

  release:
    types: [published]

  pull_request:

  workflow_dispatch:
    branches:
      - main

jobs:
  Tests:
    runs-on: ubuntu-latest
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ matrix.julia-arch }}
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - "1.6" # First compatible version
          - "1" # Latest stable version in the 1.x series
        os:
          - ubuntu-latest
        julia-arch:
          - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
